### ISSUE TITLE
Reenable UI tests

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#223]
We restructured the TravisCI build (see https://github.com/JabRef/jabref/pull/2544). Thereby, the output of the (disabled) UI tests is not visible anymore.

- [ ] Make the output of the UI tests visible again. Current output: https://travis-ci.org/JabRef/jabref/jobs/201879343
- [ ] Fix failing UI tests

https://travis-ci.org/JabRef/jabref/builds/201852127

```
net.sf.jabref.gui.importer.EntryFromFileCreatorManagerTest > testAddEntrysFromFiles SKIPPED

net.sf.jabref.gui.importer.EntryFromPDFCreatorTest > testCreationOfEntryNotInDatabase SKIPPED

net.sf.jabref.gui.importer.fetcher.OAI2HandlerFetcherTest > testParse FAILED

    java.lang.AssertionError: expected:<Optional[23 pages]> but was:<Optional.empty>

        at org.junit.Assert.fail(Assert.java:88)

        at org.junit.Assert.failNotEquals(Assert.java:834)

        at org.junit.Assert.assertEquals(Assert.java:118)

        at org.junit.Assert.assertEquals(Assert.java:144)

        at net.sf.jabref.gui.importer.fetcher.OAI2HandlerFetcherTest.testParse(OAI2HandlerFetcherTest.java:75)

net.sf.jabref.gui.importer.fetcher.OAI2HandlerFetcherTest > testOnline SKIPPED

Xlib:  extension "RANDR" missing on display ":99.0".

net.sf.jabref.gui.DialogTest2 > testCloseStyleSelectDialog STANDARD_OUT

    12:50:51.859 [AWT-EventQueue-0] INFO  net.sf.jabref.migrations.PreferencesMigrations - Upgraded old default key generator pattern '[auth][year]' to new version.

    12:50:51.876 [AWT-EventQueue-0] INFO  net.sf.jabref.migrations.PreferencesMigrations - Migrating old custom entry types.

net.sf.jabref.gui.DialogTest2 > testCloseStyleSelectDialog STANDARD_ERROR

    File: grouptree.fxml not found, attempting with camel case

    Feb 15, 2017 12:50:53 PM javafx.fxml.FXMLLoader$ValueElement processValue

    WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.111

    File: grouptree.css not found, attempting with camel case
```

**Comment by koppor** [comment]
Refs

- https://github.com/JabRef/jabref/pull/1524
- https://github.com/JabRef/jabref/pull/1700
- https://github.com/JabRef/jabref/pull/1725

**Comment by koppor** [comment]
Gui test runnter: https://github.com/JabRef/jabref/blob/master/buildres/gui-tests.sh
