### ISSUE TITLE
double click does not focus entry

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#282]
![grafik](https://user-images.githubusercontent.com/1366654/34797659-66122326-f659-11e7-8ff3-7e64173355ec.png)

**Comment by koppor** [comment]
Possibly because of

```
22:54:50.318 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.NullPointerException: null
        at org.jabref.gui.entryeditor.EntryEditor.lambda$setFocusToField$9(EntryEditor.java:264) ~[main/:?]
        at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_152]
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:?]
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[jfxrt.jar:?]
        at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177) ~[jfxrt.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
```
