### ISSUE TITLE
Entry editor is corrupted when JabRef is used intensively

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#288]
Is it possible to reload the entry editor without having to restart JabRef?

![grafik](https://user-images.githubusercontent.com/1366654/35511440-3d592be4-04fc-11e8-9259-cd62f51ff8b3.png)

<details>

```
java.lang.IllegalStateException: Not on FX application thread; currentThread = AWT-EventQueue-0
        at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:279) ~[jfxrt.jar:?]
        at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423) ~[jfxrt.jar:?]
        at javafx.stage.Window.setShowing(Window.java:939) ~[jfxrt.jar:?]
        at javafx.stage.Window.hide(Window.java:965) ~[jfxrt.jar:?]
        at javafx.stage.PopupWindow.hide(PopupWindow.java:468) ~[jfxrt.jar:?]
        at org.controlsfx.control.textfield.AutoCompletionBinding.hidePopup(AutoCompletionBinding.java:297) ~[controlsfx-8.40.15-SNAPSHOT.jar:8.40.15.SNAPSHOT]
        at org.jabref.gui.autocompleter.AutoCompletionTextInputBinding.lambda$new$1(AutoCompletionTextInputBinding.java:64) ~[main/:?]
        at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361) [jfxrt.jar:?]
        at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81) [jfxrt.jar:?]
        at javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(ReadOnlyBooleanPropertyBase.java:72) [jfxrt.jar:?]
        at javafx.scene.Node$FocusedProperty.notifyListeners(Node.java:7720) [jfxrt.jar:?]
        at javafx.scene.Scene$13.invalidated(Scene.java:2077) [jfxrt.jar:?]
        at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:111) [jfxrt.jar:?]
        at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146) [jfxrt.jar:?]
        at javafx.scene.Scene$KeyHandler.setFocusOwner(Scene.java:3924) [jfxrt.jar:?]
        at javafx.scene.Scene$KeyHandler.requestFocus(Scene.java:3971) [jfxrt.jar:?]
        at javafx.scene.Scene$KeyHandler.access$1900(Scene.java:3910) [jfxrt.jar:?]
        at javafx.scene.Scene.requestFocus(Scene.java:2044) [jfxrt.jar:?]
        at javafx.scene.Node.requestFocus(Node.java:7881) [jfxrt.jar:?]
        at org.jabref.gui.BasePanel.showAndEdit(BasePanel.java:1513) [main/:?]
        at org.jabref.gui.maintable.MainTableSelectionListener.listChanged(MainTableSelectionListener.java:106) [main/:?]
        at ca.odell.glazedlists.event.ListEventAssembler$ListEventFormat.fire(ListEventAssembler.java:424) [glazedlists_java15-1.9.1.jar:1.9.1]
        at ca.odell.glazedlists.event.ListEventAssembler$ListEventFormat.fire(ListEventAssembler.java:421) [glazedlists_java15-1.9.1.jar:1.9.1]
        at ca.odell.glazedlists.event.SequenceDependenciesEventPublisher$SubjectAndListener.firePendingEvent(SequenceDependenciesEventPublisher.java:445) [glazedlists_java15-1.9.1.jar:1.9.1]
        at ca.odell.glazedlists.event.SequenceDependenciesEventPublisher.fireEvent(SequenceDependenciesEventPublisher.java:344) [glazedlists_java15-1.9.1.jar:1.9.1]
        at ca.odell.glazedlists.event.ListEventAssembler.commitEvent(ListEventAssembler.java:317) [glazedlists_java15-1.9.1.jar:1.9.1]
        at ca.odell.glazedlists.ListSelection.commitSelected(ListSelection.java:925) [glazedlists_java15-1.9.1.jar:1.9.1]
        at ca.odell.glazedlists.ListSelection.commitAll(ListSelection.java:912) [glazedlists_java15-1.9.1.jar:1.9.1]
        at ca.odell.glazedlists.ListSelection.setSubRangeOfRange(ListSelection.java:1063) [glazedlists_java15-1.9.1.jar:1.9.1]
        at ca.odell.glazedlists.ListSelection.setSelection(ListSelection.java:730) [glazedlists_java15-1.9.1.jar:1.9.1]
        at ca.odell.glazedlists.swing.DefaultEventSelectionModel.setSelectionInterval(DefaultEventSelectionModel.java:242) [glazedlists_java15-1.9.1.jar:1.9.1]
        at javax.swing.JTable.changeSelectionModel(JTable.java:2389) [?:1.8.0_162]
        at javax.swing.JTable.changeSelection(JTable.java:2458) [?:1.8.0_162]
        at javax.swing.plaf.basic.BasicTableUI$Handler.adjustSelection(BasicTableUI.java:1115) [?:1.8.0_162]
        at javax.swing.plaf.basic.BasicTableUI$Handler.mousePressedDND(BasicTableUI.java:1080) [?:1.8.0_162]
        at javax.swing.plaf.basic.BasicTableUI$Handler.mousePressed(BasicTableUI.java:1032) [?:1.8.0_162]
        at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280) [?:1.8.0_162]
        at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279) [?:1.8.0_162]
        at java.awt.Component.processMouseEvent(Component.java:6530) [?:1.8.0_162]
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) [?:1.8.0_162]
        at java.awt.Component.processEvent(Component.java:6298) [?:1.8.0_162]
        at java.awt.Container.processEvent(Container.java:2237) [?:1.8.0_162]
        at java.awt.Component.dispatchEventImpl(Component.java:4889) [?:1.8.0_162]
        at java.awt.Container.dispatchEventImpl(Container.java:2295) [?:1.8.0_162]
        at java.awt.Component.dispatchEvent(Component.java:4711) [?:1.8.0_162]
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889) [?:1.8.0_162]
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4523) [?:1.8.0_162]
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467) [?:1.8.0_162]
        at java.awt.Container.dispatchEventImpl(Container.java:2281) [?:1.8.0_162]
        at java.awt.Window.dispatchEventImpl(Window.java:2746) [?:1.8.0_162]
        at java.awt.Component.dispatchEvent(Component.java:4711) [?:1.8.0_162]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760) [?:1.8.0_162]
        at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_162]
        at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_162]
        at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_162]
        at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_162]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) [?:1.8.0_162]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) [?:1.8.0_162]
        at java.awt.EventQueue$4.run(EventQueue.java:733) [?:1.8.0_162]
        at java.awt.EventQueue$4.run(EventQueue.java:731) [?:1.8.0_162]
        at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_162]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) [?:1.8.0_162]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:730) [?:1.8.0_162]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_162]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_162]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_162]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_162]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_162]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_162]
13:55:21.245 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.IndexOutOfBoundsException: [-2147483648, 8) is not a valid range within [0, 8)
        at org.reactfx.util.Lists.checkRange(Lists.java:128) ~[reactfx-2.0-M5.jar:?]
        at org.reactfx.util.Lists.checkRange(Lists.java:123) ~[reactfx-2.0-M5.jar:?]
        at org.reactfx.collection.MemoizationListImpl.forget(MemoizationList.java:184) ~[reactfx-2.0-M5.jar:?]
        at org.fxmisc.flowless.CellListManager.cropTo(CellListManager.java:82) ~[flowless-0.6.jar:?]
        at org.fxmisc.flowless.CellPositioner.cropTo(CellPositioner.java:29) ~[flowless-0.6.jar:?]
        at org.fxmisc.flowless.Navigator.cropToNeighborhoodOf(Navigator.java:227) ~[flowless-0.6.jar:?]
        at org.fxmisc.flowless.Navigator.placeStartAtMayCrop(Navigator.java:200) ~[flowless-0.6.jar:?]
        at org.fxmisc.flowless.Navigator.visit(Navigator.java:129) ~[flowless-0.6.jar:?]
        at org.fxmisc.flowless.StartOffStart.accept(TargetPosition.java:85) ~[flowless-0.6.jar:?]
        at org.fxmisc.flowless.Navigator.layoutChildren(Navigator.java:78) ~[flowless-0.6.jar:?]
        at javafx.scene.Parent.layout(Parent.java:1087) ~[jfxrt.jar:?]
        at org.fxmisc.flowless.VirtualFlow.layoutChildren(VirtualFlow.java:257) ~[flowless-0.6.jar:?]
        at javafx.scene.Parent.layout(Parent.java:1087) ~[jfxrt.jar:?]
        at javafx.scene.Parent.layout(Parent.java:1093) ~[jfxrt.jar:?]
        at javafx.scene.Parent.layout(Parent.java:1093) ~[jfxrt.jar:?]
        at javafx.scene.Parent.layout(Parent.java:1093) ~[jfxrt.jar:?]
        at javafx.scene.Parent.layout(Parent.java:1093) ~[jfxrt.jar:?]
        at javafx.scene.Parent.layout(Parent.java:1093) ~[jfxrt.jar:?]
        at javafx.scene.Scene.doLayoutPass(Scene.java:552) ~[jfxrt.jar:?]
        at javafx.scene.Scene.preferredSize(Scene.java:1646) ~[jfxrt.jar:?]
        at javafx.scene.Scene.impl_preferredSize(Scene.java:1720) ~[jfxrt.jar:?]
        at javafx.stage.Window$9.invalidated(Window.java:864) ~[jfxrt.jar:?]
        at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109) ~[jfxrt.jar:?]
        at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144) ~[jfxrt.jar:?]
        at javafx.stage.Window.setShowing(Window.java:940) ~[jfxrt.jar:?]
        at javafx.stage.Window.show(Window.java:955) ~[jfxrt.jar:?]
        at com.sun.javafx.stage.EmbeddedWindow.show(EmbeddedWindow.java:58) ~[jfxrt.jar:?]
        at javafx.embed.swing.JFXPanel.lambda$addNotify$51(JFXPanel.java:833) ~[jfxrt.jar:?]
        at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_162]
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:?]
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[jfxrt.jar:?]
        at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177) ~[jfxrt.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```

</details>

**Comment by tobiasdiez** [comment]
This situation should no longer occur with https://github.com/JabRef/jabref/pull/3621.

**Comment by koppor** [comment]
Current workaround: close and open library
