### ISSUE TITLE
4.3.1 preferences do not open

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#412]
```text
20:52:25.204 [AWT-EventQueue-0] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.NumberFormatException: For input string: "28.0"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_231]
        at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_231]
        at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_231]
        at org.jabref.gui.preftabs.TableColumnsTab.setValues(TableColumnsTab.java:443) ~[main/:?]
        at org.jabref.gui.preftabs.PreferencesDialog.setValues(PreferencesDialog.java:258) ~[main/:?]
        at org.jabref.gui.preftabs.PreferencesDialog.<init>(PreferencesDialog.java:206) ~[main/:?]
        at org.jabref.gui.JabRefFrame.showPreferencesDialog(JabRefFrame.java:756) ~[main/:?]
        at org.jabref.gui.JabRefFrame$ShowPrefsAction.actionPerformed(JabRefFrame.java:2092) ~[main/:?]
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) ~[?:1.8.0_231]
```

When resetting the preferences with JabRef 5.0, the preferences of 4.3.1 open again.

**Comment by Siedlerchr** [comment]
Fixed by https://github.com/JabRef/jabref/pull/6296
