### ISSUE TITLE
fix ccsb fetcher

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#499]
Query for "kopp"

http://liinwww.ira.uka.de/bibliography/rss?query=kopp&sort=scor

<details>
org.jabref.logic.importer.FetcherException: An internal parser error occurred while fetching from http://liinwww.ira.uka.de/bibliography/rss?query=kopp&sort=score
	at org.jabref/org.jabref.logic.importer.SearchBasedParserFetcher.getBibEntries(SearchBasedParserFetcher.java:52)
	at org.jabref/org.jabref.logic.importer.SearchBasedParserFetcher.performSearch(SearchBasedParserFetcher.java:41)
	at org.jabref/org.jabref.logic.importer.SearchBasedFetcher.performSearch(SearchBasedFetcher.java:48)
	at org.jabref/org.jabref.gui.importer.fetcher.WebSearchPaneViewModel.lambda$search$3(WebSearchPaneViewModel.java:124)
	at org.jabref/org.jabref.gui.importer.fetcher.WebSearchPaneViewModel$$Lambda$1771/0x00000000a294aa30.call(Unknown Source)
	at org.jabref/org.jabref.gui.util.BackgroundTask$1.call(BackgroundTask.java:59)
	at org.jabref/org.jabref.gui.util.DefaultTaskExecutor$1.call(DefaultTaskExecutor.java:160)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:853)
Caused by: org.jabref.logic.importer.ParseException: java.net.ConnectException: Connection timed out: no further information
	at org.jabref/org.jabref.logic.importer.fetcher.CollectionOfComputerScienceBibliographiesParser.parseEntries(CollectionOfComputerScienceBibliographiesParser.java:43)
	at org.jabref/org.jabref.logic.importer.SearchBasedParserFetcher.getBibEntries(SearchBasedParserFetcher.java:46)
	... 13 more
Caused by: java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1261)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1194)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1082)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1016)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1600)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1528)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at org.jabref/org.jabref.logic.net.URLDownload.openConnection(URLDownload.java:350)
	at org.jabref/org.jabref.logic.net.URLDownload.asInputStream(URLDownload.java:287)
	at org.jabref/org.jabref.logic.importer.fetcher.CollectionOfComputerScienceBibliographiesParser.parseBibtexStringsFromLinks(CollectionOfComputerScienceBibliographiesParser.java:58)
	at org.jabref/org.jabref.logic.importer.fetcher.CollectionOfComputerScienceBibliographiesParser.parseEntries(CollectionOfComputerScienceBibliographiesParser.java:37)
	... 14 more

</details>

**Comment by koppor** [comment]
Start with playing around with the class: org.jabref.logic.importer.fetcher.CollectionOfComputerScienceBibliographiesFetcherTest

Set a break point, start a debugger and do step-by-step debug

**Comment by koppor** [comment]
Tried it today, takes a long time, but no exception.
