### ISSUE TITLE
Strange NPE Exception

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#513]
```
java.lang.NullPointerException: Cannot invoke "com.sun.glass.ui.Window.isTransparentWindow()" because the return value of "com.sun.javafx.tk.quantum.WindowStage.getPlatformWindow()" is null
        at com.sun.javafx.tk.quantum.GlassScene.getClearColor(GlassScene.java:334) ~[javafx.graphics:?]
        at com.sun.javafx.tk.quantum.SceneState.update(SceneState.java:100) ~[javafx.graphics:?]
        at com.sun.javafx.tk.quantum.GlassScene.updateSceneState(GlassScene.java:277) ~[javafx.graphics:?]
        at com.sun.javafx.tk.quantum.GlassScene.releaseSynchronization(GlassScene.java:138) ~[javafx.graphics:?]
        at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2514) ~[javafx.graphics:?]
        at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:414) ~[javafx.graphics:?]
        at java.security.AccessController.doPrivileged(AccessController.java:391) ~[?:?]
        at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:413) ~[javafx.graphics:?]
        at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:440) ~[javafx.graphics:?]
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:564) ~[javafx.graphics:?]
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:544) ~[javafx.graphics:?]
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:537) ~[javafx.graphics:?]
        at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:343) ~[javafx.graphics:?]
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96) ~[javafx.graphics:?]
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[javafx.graphics:?]
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174) ~[javafx.graphics:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

```
ed in Thread[JavaFX Application Thread,5,main]                                                                    
java.lang.NullPointerException: Cannot invoke "com.sun.glass.ui.Window.isTransparentWindow()" because the return v
alue of "com.sun.javafx.tk.quantum.WindowStage.getPlatformWindow()" is null                                       
        at com.sun.javafx.tk.quantum.GlassScene.getClearColor(GlassScene.java:334) ~[javafx.graphics:?]           
        at com.sun.javafx.tk.quantum.SceneState.update(SceneState.java:100) ~[javafx.graphics:?]                  
        at com.sun.javafx.tk.quantum.GlassScene.updateSceneState(GlassScene.java:277) ~[javafx.graphics:?]        
        at com.sun.javafx.tk.quantum.GlassScene.releaseSynchronization(GlassScene.java:138) ~[javafx.graphics:?]  
        at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2514) ~[javafx.graphics:?]                      
        at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:414) ~[javafx.graphics:?]                     
        at java.security.AccessController.doPrivileged(AccessController.java:391) ~[?:?]                          
        at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:413) ~[javafx.graphics:?]                              
        at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:440) ~[javafx.graphics:?]                             
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:564) ~[javafx.graphics:?]           
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:544) ~[javafx.graphics:?]           
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:537) ~[javafx.graphics:?]  
        at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:343) ~[javafx.graphic
s:?]                                                                                                              
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96) ~[javafx.graphics:?]  
        at com.sun.glass.ui.win.WinApplication._enterNestedEventLoopImpl(Native Method) ~[javafx.graphics:?]      
        at com.sun.glass.ui.win.WinApplication._enterNestedEventLoop(WinApplication.java:201) ~[javafx.graphics:?]
        at com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:513) ~[javafx.graphics:?]           
        at com.sun.glass.ui.EventLoop.enter(EventLoop.java:107) ~[javafx.graphics:?]                              
        at com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:636) ~[javafx.graphic
s:?]                                                                                                              
        at javafx.stage.Stage.showAndWait(Stage.java:465) ~[javafx.graphics:?]                                    
        at javafx.scene.control.HeavyweightDialog.showAndWait(HeavyweightDialog.java:162) ~[javafx.controls:?]    
        at javafx.scene.control.Dialog.showAndWait(Dialog.java:346) ~[javafx.controls:?]                          
        at org.jabref.gui.JabRefDialogService.showErrorDialogAndWait(JabRefDialogService.java:192) ~[JabRef-100.0.
0.jar:?]                                                                                                          
        at org.jabref.gui.FallbackExceptionHandler.lambda$uncaughtException$0(FallbackExceptionHandler.java:26) ~[
JabRef-100.0.0.jar:?]                                                                                             
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:447) ~[javafx.graphics:?] 
        at java.security.AccessController.doPrivileged(AccessController.java:391) ~[?:?]                          
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:446) ~[javafx.graphics:?] 
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96) ~[javafx.graphics:?]  
        at com.sun.glass.ui.win.WinApplication._enterNestedEventLoopImpl(Native Method) ~[javafx.graphics:?]      
        at com.sun.glass.ui.win.WinApplication._enterNestedEventLoop(WinApplication.java:201) ~[javafx.graphics:?]
        at com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:513) ~[javafx.graphics:?]           
        at com.sun.glass.ui.EventLoop.enter(EventLoop.java:107) ~[javafx.graphics:?]                              
        at com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:636) ~[javafx.graphic
s:?]                                                                                                              
        at javafx.stage.Stage.showAndWait(Stage.java:465) ~[javafx.graphics:?]                                    
        at javafx.scene.control.HeavyweightDialog.showAndWait(HeavyweightDialog.java:162) ~[javafx.controls:?]    
        at javafx.scene.control.Dialog.showAndWait(Dialog.java:346) ~[javafx.controls:?]                          
        at org.jabref.gui.JabRefDialogService.showErrorDialogAndWait(JabRefDialogService.java:192) ~[JabRef-100.0.
0.jar:?]                                                                                                          
        at org.jabref.gui.FallbackExceptionHandler.lambda$uncaughtException$0(FallbackExceptionHandler.java:26) ~[
JabRef-100.0.0.jar:?]                                                                                             
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:447) ~[javafx.graphics:?] 
        at java.security.AccessController.doPrivileged(AccessController.java:391) ~[?:?]                          
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:446) ~[javafx.graphics:?] 
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96) ~[javafx.graphics:?]  
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[javafx.graphics:?]                       
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174) ~[javafx.graphics:?]     
        at java.lang.Thread.run(Thread.java:831) [?:?]                                                            
```

**Comment by koppor** [comment]
![grafik](https://user-images.githubusercontent.com/1366654/129612211-27bfd219-d762-463a-a19e-094ccb33e7fa.png)

After focus loss:

![grafik](https://user-images.githubusercontent.com/1366654/129612239-8020ec22-a246-4652-84cf-df7db4d88212.png)

**Comment by koppor** [comment]
Retry after https://github.com/JabRef/jabref/pull/7981 is merged.
