### ISSUE TITLE
Adding a PDF should not lead to exception

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#565]
I try to import the PDF of https://www.iaas.uni-stuttgart.de/publications/ART-2016-26_The-OpenTOSCA-Ecosystem-Concepts-and-Tools.pdf

![grafik](https://user-images.githubusercontent.com/1366654/169531150-a8e5388d-6328-4331-bba5-16b873d2b414.png)

I am using the GROBID service

I get the following exception:

```
java.lang.IllegalArgumentException: prefix cannot be "null" when creating a QName
	at java.xml/javax.xml.namespace.QName.<init>(QName.java:192)
	at xmpbox@3.0.0-RC1/org.apache.xmpbox.xml.DomHelper.getQName(DomHelper.java:99)
	at xmpbox@3.0.0-RC1/org.apache.xmpbox.xml.DomXmpParser.parseChildrenAsProperties(DomXmpParser.java:304)
	at xmpbox@3.0.0-RC1/org.apache.xmpbox.xml.DomXmpParser.parseDescriptionRoot(DomXmpParser.java:248)
	at xmpbox@3.0.0-RC1/org.apache.xmpbox.xml.DomXmpParser.parse(DomXmpParser.java:201)
	at org.jabref@100.0.0/org.jabref.logic.xmp.XmpUtilShared.parseXmpMetadata(XmpUtilShared.java:31)
	at org.jabref@100.0.0/org.jabref.logic.xmp.XmpUtilReader.getXmpMetadata(XmpUtilReader.java:130)
	at org.jabref@100.0.0/org.jabref.logic.xmp.XmpUtilReader.readXmp(XmpUtilReader.java:66)
	at org.jabref@100.0.0/org.jabref.logic.importer.fileformat.PdfXmpImporter.importDatabase(PdfXmpImporter.java:57)
	at org.jabref@100.0.0/org.jabref.logic.importer.fileformat.PdfMergeMetadataImporter.importDatabase(PdfMergeMetadataImporter.java:80)
	at org.jabref@100.0.0/org.jabref.logic.importer.ImportFormatReader.lambda$importUnknownFormat$0(ImportFormatReader.java:185)
	at org.jabref@100.0.0/org.jabref.logic.importer.ImportFormatReader.importUnknownFormat(ImportFormatReader.java:227)
	at org.jabref@100.0.0/org.jabref.logic.importer.ImportFormatReader.importUnknownFormat(ImportFormatReader.java:185)
	at org.jabref@100.0.0/org.jabref.gui.importer.ImportAction.doImport(ImportAction.java:126)
	at org.jabref@100.0.0/org.jabref.gui.importer.ImportAction.lambda$automatedImport$1(ImportAction.java:65)
	at org.jabref@100.0.0/org.jabref.gui.util.BackgroundTask$1.call(BackgroundTask.java:60)
	at org.jabref@100.0.0/org.jabref.gui.util.DefaultTaskExecutor$1.call(DefaultTaskExecutor.java:161)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by koppor** [comment]
good third issue
