### ISSUE TITLE
SLR: Create a new different study in an existing folder

### ISSUE THREAD

**Issue by Siedlerchr** [koppor/jabref#613]
1. Create a new study, select a  new folder e..g Study
3. Create another different study, select the same folder as above.

E```
xception occurs:
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "last-search-date" (class org.jabref.model.study.Study), not marked as ignorable (5 known properties: "authors", "research-questions", "queries", "title", "databases"])
 at [Source: (FileInputStream); line: 4, column: 29] (through reference chain: org.jabref.model.study.Study["last-search-date"])
	at com.fasterxml.jackson.databind@2.13.3/com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind@2.13.3/com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)
	at com.fasterxml.jackson.databind@2.13.3/com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2023)
	at com.fasterxml.jackson.databind@2.13.3/com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700)
	at com.fasterxml.jackson.databind@2.13.3/com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1678)
	at com.fasterxml.jackson.databind@2.13.3/com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:319)
	at com.fasterxml.jackson.databind@2.13.3/com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
	at com.fasterxml.jackson.databind@2.13.3/com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind@2.13.3/com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind@2.13.3/com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3666)
	at org.jabref/org.jabref.logic.crawler.StudyYamlParser.parseStudyYamlFile(StudyYamlParser.java:25)
	at org.jabref/org.jabref.logic.crawler.StudyRepository.<init>(StudyRepository.java:121)
	at org.jabref/org.jabref.logic.crawler.Crawler.<init>(Crawler.java:52)
	at org.jabref/org.jabref.gui.slr.ExistingStudySearchAction.crawl(ExistingStudySearchAction.java:109)
	at org.jabref/org.jabref.gui.slr.StartNewStudyAction.execute(StartNewStudyAction.java:41)
	at org.jabref/org.jabref.gui.actions.JabRefAction.lambda$3(JabRefAction.java:40)
	at org.controlsfx.controls/org.controlsfx.control.action.Action.handle(Action.java:423)
	at org.controlsfx.controls/org.controlsfx.control.action.Action.handle(Action.java:64)
	at javafx.base@18.0.2/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base@18.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at javafx.base@18.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base@18.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@18.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18.0.2/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@18.0.2/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base@18.0.2/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.controls@18.0.2/javafx.scene.control.MenuItem.fire(MenuItem.java:459)
	at javafx.controls@18.0.2/com.sun.javafx.scene.control.GlobalMenuAdapter.lambda$bindMenuItemProperties$2(GlobalMenuAdapter.java:153)
	at javafx.base@18.0.2/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base@18.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at javafx.base@18.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base@18.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@18.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18.0.2/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@18.0.2/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base@18.0.2/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.controls@18.0.2/javafx.scene.control.MenuItem.fire(MenuItem.java:459)
	at javafx.graphics@18.0.2/com.sun.javafx.tk.quantum.GlassSystemMenu$1.action(GlassSystemMenu.java:234)

```

**Comment by koppor** [comment]
Partially addressed by https://github.com/JabRef/jabref/pull/9124.

We need to check the behavior of using existing SLR directories. - IMHO JabRef should issue a warning and completely reset the directory.

**Comment by koppor** [comment]
Starting a new SLR in an existing directory is not possible - https://github.com/koppor/jabref/issues/620

One needs to start at an empty directory.

We request the user to delete the files for themselves.
