### ISSUE TITLE
SPIRES search does'n work

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#65]
I try to search for `lalala` and I get following result:

![grabbed_20151129-140818](https://cloud.githubusercontent.com/assets/1366654/11457187/a8846e8a-96a2-11e5-9af0-2585bd362e60.png)

```
java.lang.NullPointerException
	at net.sf.jabref.importer.fetcher.SPIRESFetcher.processQuery(SPIRESFetcher.java:199)
	at net.sf.jabref.importer.fetcher.GeneralFetcher$4.run(GeneralFetcher.java:288)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by koppor** [comment]
SPIRES homepage: https://www.slac.stanford.edu/spires/about/, but http://www.slac.stanford.edu/spires/ links to http://inspirehep.net/. Therefore, we drop this fetcher.

Also backed by Wikipedia: "SPIRES is, as of 2012, being replaced by INSPIRE-HEP" (https://en.wikipedia.org/wiki/Stanford_Physics_Information_Retrieval_System)

**Comment by matthiasgeiger** [comment]
Removed from codebase in fd6b4f9af11fdc681041f2abe663cc44597bbec9
